# Add your imprint or brand name here, it will appear in navigation.
publisher: "Publisher name"

# Your publisher name will link to this URL in navigation.
publisher-url: "http://electricbookworks.com"

# The name of the collection or series in this repo.
name: "Series name"

# A one-liner about this collection. Useful for Open Graph metadata.
description: "A description of this series or collection"

# The primary language of the books in this collection.
language: en

# Leave this unchanged as http://localhost:4000 unless you really know what you're doing here. This is the URL that Jekyll will run at by default locally.
url: http://localhost:4000

# Change this to the name of your collection repo, e.g. /my-cool-books
baseurl: /book-framework

# Leave this unchanged as kramdown unless you really know how and why to change your markdown processor
markdown: kramdown

# Leave this unchanged as none. This way, your book's chapters will all generate correctly named in one folder, really useful for grabbing them all at once, e.g. for sending to PrinceXML for PDF.
permalink: none

# Users with GitHub contributor access can edit your book with http://prose.io. These settings control what they see. See https://github.com/prose/prose/wiki/Prose-Configuration for more info.
prose: 
  rooturl: 'book-framework'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /css

# These are default YAML values that apply to multiple documents. 
defaults: 
    -
        scope: # Set the filename of each book's outputted contents page for use in navigation. For technical details, see http://jekyllrb.com/docs/configuration/#front-matter-defaults
            path: "book-one" # the folder for a book
        values:
            contents: "0-3-contents.html" # the filename of its contents page
    -
        scope: # Set the contents-page filename for each book in the collection separately.
            path: "book-two" # the folder for a book
        values:
            contents: "0-4-contents.html" # the filename of its contents page
    -
        scope: # Let's set the default page layout, for when a layout specified in a page's YAML header doesn't exist.
            path: "" # an empty string here means all files in the project
        values:
            layout: "default"