# Add your imprint or brand name here, it will appear in navigation.
publisher: "Publisher name"

# Your publisher name will link to this URL in navigation.
publisher-url: "http://electricbookworks.com"

# The name of the collection or series in this repo.
name: "Series name"

# A one-liner about this collection. Useful for Open Graph metadata.
description: "A description of this series or collection"

# The primary language used in this collection. Set the language for each book below. Use ISO 639-1 two-letter codes: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
language: en

# Leave this unchanged as http://localhost:4000 unless you really know what you're doing here. This is the URL that Jekyll will run at by default locally.
url: http://localhost:4000

# Change this to the name of your collection repo, e.g. /my-cool-books
baseurl: /book-framework

# Leave this unchanged as kramdown unless you really know how and why to change your markdown processor
markdown: kramdown

# Leave this unchanged as none. This way, your book's chapters will all generate correctly named in one folder, really useful for grabbing them all at once, e.g. for sending to PrinceXML for PDF.
permalink: none

# These are default YAML values that apply to multiple documents. (For technical details, see http://jekyllrb.com/docs/configuration/#front-matter-defaults)
defaults: 
    -
        scope: # First we set defaults for all pages (an empty string "" for path means all files).
            path: ""
        values:
            layout: "default"
            style: "chapter"
            stylesheet: "screen.css"
            stylesheet-child: ""
            contents: "0-3-contents.html"
            language: "en"
    -
        scope: # Now enter details for your first book. The `path` is the book's folder. The `values` are specific to the book in that folder.
            path: "book-one"
        values:
            book-title: "Book title"
            language: "en"
            layout: "default"
            style: "chapter"
            stylesheet: "screen.css"
            stylesheet-child: ""
            contents: "0-3-contents.html"
    -
        scope: # Repeat for each book.
            path: "book-two"
        values:
            book-title: "Book two title"
            language: "en"
            layout: "default"
            style: "chapter"
            stylesheet: "screen.css"
            stylesheet-child: "screen-child-book-two.css"
            contents: "0-3-contents.html"

# Users with GitHub contributor access can edit your book with http://prose.io. These settings control what they see. See https://github.com/prose/prose/wiki/Prose-Configuration for more info.
prose: 
#  siteurl: "http://electricbookworks.github.io/book-framework"
  ignore:
    - .gitattributes
    - .gitignore
    - _config.yml
    - /_layouts
    - /_includes
    - /_site
    - /css
  media: "downloads"
  metadata:
    "":
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "style"
        field:
          element: "select"
          label: "Page style"
          placeholder: "Select page style"
          options:
            - name: "Chapter"
              value: "chapter"
            - name: "Collection home page"
              value: "index"
            - name: "Cover"
              value: "cover"
            - name: "Half-title page"
              value: "halftitle-page"
            - name: "Title page"
              value: "title-page"
            - name: "Copyright page"
              value: "copyright-page"
            - name: "Contents page"
              value: "contents-page"
            - name: "Dedication page"
              value: "dedication-page"
            - name: "Epigraph page"
              value: "epigraph-page"
            - name: "Other frontmatter"
              value: "frontmatter"
