# Add your imprint or brand name here, it will appear in navigation.
publisher: "Publisher name"

# Your publisher name will link to this URL in navigation.
publisher-url: "http://electricbookworks.com"

# The name of the collection or series in this repo.
name: "Series name"

# A one-liner about this collection. Useful for Open Graph metadata.
description: "A description of this series or collection"

# The primary language of the books in this collection.
language: en

# Leave this unchanged as http://localhost:4000 unless you really know what you're doing here. This is the URL that Jekyll will run at by default locally.
url: http://localhost:4000

# Change this to the name of your collection repo, e.g. /my-cool-books
baseurl: /book-framework

# Leave this unchanged as kramdown unless you really know how and why to change your markdown processor
markdown: kramdown

# Leave this unchanged as none. This way, your book's chapters will all generate correctly named in one folder, really useful for grabbing them all at once, e.g. for sending to PrinceXML for PDF.
permalink: none

# Users with GitHub contributor access can edit your book with http://prose.io. These settings control what they see. See https://github.com/prose/prose/wiki/Prose-Configuration for more info.
prose: 
  rooturl: 'book-framework'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /css

# These are default YAML values that apply to multiple documents. (For technical details, see http://jekyllrb.com/docs/configuration/#front-matter-defaults)
defaults: 
    -
        scope: # First we set defaults for all pages (an empty string "" for path means all files).
            path: ""
        values:
            layout: "default"
            stylesheet: "screen.css"
            contents: "0-3-contents.html"
    -
        scope: # Now, for each book's folder, override/add its HTML contents page and any new and/or child stylesheets.
            path: "book-one"
        values:
            contents: "0-3-contents.html"
            stylesheet: "screen.css"
            stylesheet-child: ""
    -
        scope: # Repeat for each book, once for book's folder, which is the path variable here.
            path: "book-two"
        values:
            contents: "0-3-contents.html"
            stylesheet: "screen.css"
            stylesheet-child: "screen-child-book-two.css"