# Add your imprint or brand name here, it will appear in navigation.
publisher: "Publisher name"

# Your publisher name will link to this URL in navigation.
publisher-url: "http://electricbookworks.com"

# The name of the collection of books in this repo.
name: "Collection name"

# A one-liner about this collection. Useful for Open Graph metadata.
description: "A description of this collection"

# The primary language used in this collection. You can set the language for each book below at 'defaults'. 
# To understand what tags to use, read: http://www.w3.org/International/articles/language-tags/ 
# For the registry of tags: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry 
# Useful lookup tool: http://r12a.github.io/apps/subtags/
language: en

# Leave this unchanged as http://localhost:4000 unless you really know what you're doing here. This is the URL that Jekyll will run at by default locally.
url: http://localhost:4000

# Change this to the name of your collection repo, e.g. /my-cool-books
baseurl: /book-framework

# Leave this unchanged as kramdown unless you really know how and why to change your markdown processor
markdown: kramdown

# Leave this unchanged as none. This way, your book's chapters will all generate correctly named in one folder, really useful for grabbing them all at once, e.g. for sending to PrinceXML for PDF.
permalink: none

# These are default YAML values that apply to multiple documents. (For technical details, see http://jekyllrb.com/docs/configuration/#front-matter-defaults).
defaults: 
    -
        scope: # First we set defaults for all pages (an empty string "" for path means all files).
            path: ""
        values:
            book-title: "Collection name"
            author: "A. N. Author"
            language: "en"
            publication-date: "2015-12-01"
            layout: "default"
            style: "chapter"
            stylesheet: "screen.css"
            stylesheet-child: ""
            contents: "0-3-contents.html"
            language: "en"
            isbn-print: ""
            isbn-epub: ""
            uuid: ""
    -
        scope: # Now enter details for your first book. The `path` is the book's folder. The `values` are specific to the book in that folder. Add values to override the defaults above per book. Remember to indent with spaces, not tabs, for valid YAML.
            path: "book-one"
        values:
            book-title: "Book title"
    -
        scope: # Repeat for each book.
            path: "book-two"
        values:
            book-title: "Book two title"
            stylesheet-child: "screen-child-book-two.css"
