publisher: "Electric Book Works"
publisher-url: "http://electricbookworks.com"
name: "This collection's name"
description: "A description of this collection"

url: http://localhost:4000
baseurl: /book-framework

paginate: 10

markdown: kramdown
permalink: none
highlighter: pygments