publisher: "Electric Book Works"
publisher-url: "http://electricbookworks.com"
name: "Book framework"
description: "Your subtitle here"

url: http://localhost:4000
baseurl: /book-framework

paginate: 10

markdown: kramdown
permalink: none
highlighter: pygments