publisher: "Publisher name"
publisher-url: "http://electricbookworks.com"
name: "Series name"
description: "A description of this series or collection"
language: en

url: http://localhost:4000
baseurl: /book-framework

paginate: 10

markdown: kramdown
permalink: none
highlighter: pygments

prose: # these settings are for editing in prose.io: https://github.com/prose/prose/wiki/Prose-Configuration
  rooturl: 'book-framework'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /css