########
# SERIES
########

series:
  # The name of the organisation or entity that owns this series
  organisation: "Electric Book Works"
  # A live web address for the organisation
  url: "https://electricbookworks.com/"
  # The name of the series of books in this folder.
  name: "The Electric Book Workflow"
  # A one-liner about this series. Useful for Open Graph metadata.
  description: "A workflow for creating high-quality books and ebooks with open technologies."

########
# TITLES
########

## Metadata follows [Dublin Core](https://en.wikipedia.org/wiki/Dublin_Core#DCMI_Metadata_Terms)
## Custom fields added to standard DC terms: subtitle, publisher URL
## When listing files, exlude file extensions, and surround them in quotes especially if they contain only numbers.

works:
  - directory: "guide"
    title: "A Guide to the Electric Book Workflow"
    subtitle: "How to create high-quality books with open tools"
    creator: "Arthur Attwell" # E.g. the author
    contributor: "" # E.g. other contributors
    subject: "Publishing" # E.g. BISAC terms (https://www.bisg.org/bisac/bisac-subject-codes) or BIC (http://editeur.dyndns.org/bic_categories)
    description: "The Electric Book Workflow is a set of tools and processes for creating high-quality books with (mostly) free, open technologies. We developed it at Electric Book Works for our own publishing. It allows you to store books in plain text with great version control, and to output website versions, ebooks and print editions easily from a single source. With some technical expertise, you can implement it, too. This guide is created with the workflow." # E.g. the blurb
    publisher: "Electric Book Works" # E.g. the publisher, imprint or brand name
    publisher-url: ""
    date: "2015-12-31" # YYYY-MM-DD e.g. publication date
    modified: "2016-08-30" # YYYY-MM-DD e.g. date of last revision
    type: "Novel" # e.g. Novel, Poetry, Memoir
    identifier: "978-1-928313-13-7" # e.g. ISBN or UUID
    source: "978-1-928313-13-7" # e.g. parent ISBN or ISTC
    language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
    relation: "" # e.g. other edition ISBN
    coverage: "" # e.g. geographic place or chronological time span
    rights: "This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/). This means you are free to share (copy and redistribute the material in any medium or format) and adapt it (remix, transform, and build upon the material) for any purpose, even commercially, as long as you give appropriate credit, with a link to your source, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use." # e.g. a copyright statement
    products: # Metadata for each product for this title (only use values that override parent metadata)
      print-pdf: 
        date: "2016-05-07" # YYYY-MM-DD e.g. publication or creation date
        format: "Print" # e.g. Paperback, Digital download, Digital online
        identifier: "" # e.g. ISBN or UUID
        files:
          - 0-1-titlepage
          - 0-2-copyright
          - 0-3-contents
          - 0-4-preface
          - 0-9-quick-start
          - 01-intro
          - 02-setting-up
          - 03-markdown
          - 04-themes
          - 05-classes
          - 10-tocs
          - 15-images
          - 16-video
          - 17-notes
          - 18-tables
          - 19-indexes
          - 20-poetry
          - 25-page-numbers
          - 30-javascript
          - 40-indd-to-md
          - 50-print-output
          - 51-epub-output
          - 60-troubleshooting
          - 70-examples
      web:
        date: "2016-08-30" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital online" # e.g. Paperback, Digital download, Digital online
        identifier: "978-1-928313-14-4" # e.g. ISBN or UUID
        files: # To add a file to web navigation, give a file a value, e.g. 0-4-preface: "Preface"
          - 0-1-titlepage
          - 0-2-copyright
          - 0-3-contents
          - 0-4-preface
          - 0-9-quick-start: "Quick start"
          - 01-intro: "Introduction"
          - 02-setting-up: "Setting up"
          - 03-markdown: "Markdown"
          - 04-themes: "Themes"
          - 05-classes: "Classes"
          - 10-tocs: "Tables of contents"
          - 15-images: "Images"
          - 16-video: "Video"
          - 17-notes: "Notes"
          - 18-tables: "Tables"
          - 19-indexes: "Indexes"
          - 20-poetry: "Poetry"
          - 25-page-numbers: "Page numbers"
          - 30-javascript: "Javascript"
          - 40-indd-to-md: "InDesign conversion"
          - 50-print-output: "Print output"
          - 51-epub-output: "Epub output"
          - 60-troubleshooting: "Troubleshooting"
          - 70-examples: "Examples"
        start-page: "0-3-contents" # At which file should users start reading?
        contents-page: "0-3-contents" # Your contents-page file, if you have one.
        footer: "Built with an <a href='http://electricbook.io'>Electric Book</a>" # Text that appears in the footer of the website. You can include HTML.
      epub:
        date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "978-1-928313-14-4" # e.g. ISBN or UUID
        files:
          - 0-0-cover
          - 0-1-titlepage
          - 0-2-copyright
          - 0-3-contents
          - 0-4-preface
          - 0-9-quick-start
          - 01-intro
          - 02-setting-up
          - 03-markdown
          - 04-themes
          - 05-classes
          - 10-tocs
          - 15-images
          - 16-video
          - 17-notes
          - 18-tables
          - 19-indexes
          - 20-poetry
          - 25-page-numbers
          - 30-javascript
          - 40-indd-to-md
          - 50-print-output
          - 51-epub-output
          - 60-troubleshooting
          - 70-examples
      screen-pdf:
        date: "2016-08-30" # YYYY-MM-DD e.g. publication date or last revision
        format: "Digital download" # e.g. Paperback, Digital download, Digital online
        identifier: "978-1-928313-14-4" # e.g. ISBN or UUID
        files:
          - 0-0-cover
          - 0-1-titlepage
          - 0-2-copyright
          - 0-3-contents
          - 0-4-preface
          - 0-9-quick-start
          - 01-intro
          - 02-setting-up
          - 03-markdown
          - 04-themes
          - 05-classes
          - 10-tocs
          - 15-images
          - 16-video
          - 17-notes
          - 18-tables
          - 19-indexes
          - 20-poetry
          - 25-page-numbers
          - 30-javascript
          - 40-indd-to-md
          - 50-print-output
          - 51-epub-output
          - 60-troubleshooting
          - 70-examples
